[project]
name = "cli-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mypy>=1.17.0",
    "prompt-toolkit>=3.0.51",
]
